---
- hosts: rt
  gather_facts: false

  tasks:
    # HSRP の設定
    - name: set HSRP
      cisco.ios.ios_config:
        lines:
          - standby version 2
          - standby 1 ip 10.1.1.254
          - standby 1 priority 110
        parents:
          - interface GigabitEthernet0/3
