---
- hosts: rt
  gather_facts: false

  tasks:
    # ログインバナーの設定
    - name: set banner
      cisco.ios.ios_banner:
        banner: login
        text: |-
          --------- NOTICE ---------
            PRODUCTION environment
          --------------------------
        state: present
