---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: create vm
      community.vmware.vmware_guest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        folder: /vm/F0
        name: new-vm01
        guest_id: centos8_64Guest
        hardware:
          num_cpus: 2
          num_cpu_cores_per_socket: 2
          memory_mb: 1024
        cdrom:
          - controller_number: 0
            unit_number: 0
            iso_path: "[nfs_ds01] ISO/CentOS-8.3.2011-x86_64-minimal.iso"
            type: iso
        disk:
          - size_gb: 32
            type: thin
            datastore: nfs_ds01
        networks:
          - name: VM Network
        state: poweredon
