---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: copy file to vm
      community.vmware.vmware_guest_file_operation:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        folder: /vm/F0
        vm_id: new-vm01
        vm_username: root
        vm_password: P@ssw0rd
        copy:
          src: "{{ inventory_dir }}/test.zip"
          dest: "/tmp/test.zip"
          overwrite: true
