---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: export ovf
      community.vmware.vmware_export_ovf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        folder: /vm/F0
        name: new-vm01
        export_dir: "{{ inventory_dir }}/export_ovf"
