---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: execute touch command
      community.vmware.vmware_vm_shell:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        folder: /vm/F0
        vm_id: new-vm01
        vm_username: root
        vm_password: P@ssw0rd
        vm_shell: /bin/touch
        vm_shell_args: "test_file.txt"
        vm_shell_cwd: /tmp
