---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: create snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        folder: /vm/F0
        name: new-vm01
        snapshot_name: snapshot01
        state: present
