---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: make and fetch vm screenshot
      community.vmware.vmware_guest_screenshot:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        folder: /vm/F0
        name: new-vm01
        local_path: "{{ inventory_dir }}/screenshot"
