---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: execute touch command
      community.vmware.vmware_vm_shell:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        folder: /vm/F0
        vm_id: win-vm01
        vm_username: administrator
        vm_password: P@ssw0rd
        vm_shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        vm_shell_args: "New-Item -Type File test_file.txt"
        vm_shell_cwd: C:\Users\Administrator\Desktop
