---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: add ESXi host to dvs
      community.vmware.vmware_dvs_host:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        switch_name: dvswitch01
        esxi_hostname: esxi-001.local
        vmnics:
          - vmnic2
          - vmnic3
        state: present
