---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: gather categories
      community.vmware.vmware_category_info:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: gather_categories_result

    - name: display categories
      debug:
        msg: "{{ gather_categories_result }}"
