---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: add ESXi host
      community.vmware.vmware_host:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: DC01
        cluster: Cluster01
        esxi_hostname: esxi-001.local
        esxi_username: root
        esxi_password: "{{ esxi_password }}"
        state: present
