---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: create cluster
      community.vmware.vmware_cluster:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter_name: DC01
        cluster_name: Cluster01
        state: present
