---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: assign license for ESXi
      community.vmware.vcenter_license:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        license: "{{ esxi_license }}"
        state: present
