---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: enter maintenance mode
      community.vmware.vmware_maintenancemode:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        esxi_hostname: esxi-001.local
        evacuate: true
        state: present
