---
- hosts: vcenter
  gather_facts: false
  tasks:
    - name: enable DRS
      community.vmware.vmware_cluster_drs:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter_name: DC01
        cluster_name: Cluster01
        enable_drs: true
        drs_default_vm_behavior: fullyAutomated
        drs_enable_vm_behavior_overrides: true
        drs_vmotion_rate: 1
