---
- hosts: sv
  gather_facts: false
  vars:
    sample_password: my_password

  tasks:
    - name: password_hash sample
      ansible.builtin.debug:
        msg: "{{ sample_password | ansible.builtin.password_hash }}"

    - name: password_hash sample with type and salt
      ansible.builtin.debug:
        msg: "{{ sample_password | ansible.builtin.password_hash('sha256', 'salt/str') }}"
