---
- hosts: sv
  gather_facts: false

  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: task1
      tags:
        - tag1
        - tag2

    - name: task2
      ansible.builtin.debug:
        msg: task2
      tags:
        - tag2
        - tag3
