---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false

  tasks:
    - name: change connection limit
      f5networks.f5_modules.bigip_node:
        state: present
        name: web_node001
        address: 10.100.0.135
        monitors: /Common/icmp
        availability_requirements:
          type: all
        connection_limit: 100
