---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false

  tasks:
    - name: offline pool member
      f5networks.f5_modules.bigip_pool_member:
        state: forced_offline
        pool: http_pool_1
        aggregate:
          - name: web_node001
            address: 10.100.0.135
            port: 80
